flags:
  text:
    integer-simple: false
packages:
- '.'
extra-deps:
- MonadRandom-0.4
- StateVar-1.1.0.1
- aeson-0.9.0.1
- aeson-pretty-0.7.2
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- appar-0.1.4
- asn1-encoding-0.9.2
- asn1-parse-0.9.1
- asn1-types-0.3.0
- async-2.0.2
- attoparsec-0.13.0.1
- auto-update-0.1.2.2
- base-orphans-0.4.4
- base64-bytestring-1.0.0.1
- bifunctors-5
- blaze-builder-0.4.0.1
- blaze-html-0.8.1.0
- blaze-markup-0.7.0.2
- byteable-0.1.1
- byteorder-1.0.4
- bytestring-builder-0.10.6.0.0
- bytestring-conversion-0.3.1
- case-insensitive-1.2.0.4
- cereal-0.4.1.1
- cmdargs-0.10.13
- comonad-4.2.7.2
- conduit-1.2.5
- conduit-extra-1.1.9.1
- connection-0.2.5
- contravariant-1.3.3
- cookie-0.4.1.6
- cryptohash-0.11.6
- cryptohash-conduit-0.1.1
- cryptonite-0.7
- data-default-class-0.0.1
- distributive-0.4.4
- dlist-0.7.1.2
- double-conversion-2.0.1.0
- easy-file-0.2.1
- either-4.4.1
- exceptions-0.8.0.2
- fast-logger-2.4.1
- file-embed-0.0.9
- free-4.12.1
- hashable-1.2.3.3
- hex-0.1.2
- hourglass-0.2.9
- http-client-0.4.22
- http-client-tls-0.2.2
- http-date-0.0.6.1
- http-media-0.6.2
- http-types-0.8.6
- http2-1.0.4
- iproute-1.6.0
- lifted-base-0.2.3.6
- memory-0.10
- mime-types-0.1.0.6
- mmorph-1.0.4
- monad-control-1.0.0.4
- mtl-2.2.1
- mwc-random-0.13.3.2
- nats-1
- network-2.6.2.1
- network-uri-2.6.0.3
- old-locale-1.0.0.7
- old-time-1.1.0.3
- opaleye-0.4.1.0
- optparse-applicative-0.11.0.2
- parsec-3.1.9
- pem-0.2.2
- prelude-extras-0.4.0.2
- primitive-0.6
- profunctors-5.1.1
- random-1.1
- resourcet-1.1.6
- safe-0.3.9
- scientific-0.3.3.8
- semigroupoids-5.0.0.4
- semigroups-0.16.2.2
- servant-0.4.4.2
- servant-client-0.4.4.2
- servant-server-0.4.4.2
- simple-sendfile-0.2.21
- socks-0.5.4
- split-0.2.2
- stm-2.4.4
- streaming-commons-0.1.13
- string-conversions-0.4
- stringsearch-0.3.6.6
- syb-0.5.1
- system-filepath-0.4.13.4
- tagged-0.8.1
- text-1.2.1.3
- tls-1.3.2
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- unix-compat-0.4.1.4
- unix-time-0.3.5
- unordered-containers-0.2.5.1
- utf8-string-1.0.1.1
- vault-0.3.0.4
- vector-0.11.0.0
- void-0.7
- wai-3.0.3.0
- wai-app-static-3.1.1
- wai-extra-3.0.10
- wai-logger-2.2.4.1
- warp-3.1.3
- word8-0.1.2
- x509-1.6.1
- x509-store-1.6.1
- x509-system-1.6.1
- x509-validation-1.6.2
- zlib-0.6.1.1
resolver: lts-3.2
